apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "kapacitor"
  labels:
    app: "kapacitor"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: "kapacitor"
        name: "kapacitor"
        app: "kapacitor"
    spec:
      containers:
        - name: "kapacitor"
          image: "kapacitor:1.0.0-beta1"
          env:
            - name: KAPACITOR_HOSTNAME
              value: "kapacitor.kube-system.svc.cluster.local"
            - name: KAPACITOR_LOGGING_LEVEL
              value: "INFO"
            - name: KAPACITOR_REPORTING_ENABLED
              value: "false"
            - name: KAPACITOR_INFLUXDB_0_URLS_0
              value: "http://influxdb.kube-system.svc.cluster.local:8086/"
            - name: KAPACITOR_LOGGING_LEVEL
              value: "DEBUG"
          ports:
            - containerPort: 9092
            - containerPort: 43309
              protocol: UDP
              name: udp
          imagePullPolicy: "Always"
