apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    name: stream
  - port: 43309
    protocol: UDP
    targetPort: 43309
    name: subscription
  selector:
    app: kapacitor
